api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    # The active versions of OpenAPI to be exported or used in the swagger_ui. The first value is the default.
    versions: [ 3 ]
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]
    multipart: ['multipart/form-data']
