vich_uploader:
        db_driver: orm # Or mongodb or propel
        metadata:
          type: attribute
        mappings:
            categorie_image:
                uri_prefix: /images/categorie
                upload_destination: '%kernel.project_dir%/public/images/categorie'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
                delete_on_update: false
                delete_on_remove: false
            produit_image:
                uri_prefix: /images/produits
                upload_destination: '%kernel.project_dir%/public/images/produits'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
                delete_on_update: false
                delete_on_remove: false
            sous_categorie:
              uri_prefix: /images/sousCategories
              upload_destination: '%kernel.project_dir%/public/images/sousCategories'
              namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
              delete_on_update: false
              delete_on_remove: false


