vich_uploader:
        db_driver: orm # Or mongodb or propel
        metadata:
          type: attribute
        mappings:
            categorie_image:
                uri_prefix: /images/categorie
                upload_destination: '%kernel.project_dir%/public/images/categorie'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
                delete_on_update: false
                delete_on_remove: false
